// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: executions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countExecutions = `-- name: CountExecutions :one
SELECT count(*) FROM execution_logs
WHERE org_id = $1
  AND ($2::text = '' OR template_name = $2)
  AND ($3::text = '' OR status = $3)
`

type CountExecutionsParams struct {
	OrgID    uuid.UUID `json:"orgId"`
	Template string    `json:"template"`
	Status   string    `json:"status"`
}

func (q *Queries) CountExecutions(ctx context.Context, arg CountExecutionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExecutions, arg.OrgID, arg.Template, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExecutionLog = `-- name: CreateExecutionLog :one
INSERT INTO execution_logs
    (org_id, template_name, template_title, status, commit_sha, commit_url, error_message,
     values_json, files_created, output_target, output_repo, duration_ms)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, org_id, template_name, template_title, status, commit_sha, commit_url, error_message, values_json, files_created, output_target, output_repo, executed_at, duration_ms
`

type CreateExecutionLogParams struct {
	OrgID         uuid.UUID   `json:"orgId"`
	TemplateName  string      `json:"templateName"`
	TemplateTitle string      `json:"templateTitle"`
	Status        string      `json:"status"`
	CommitSha     pgtype.Text `json:"commitSha"`
	CommitUrl     pgtype.Text `json:"commitUrl"`
	ErrorMessage  pgtype.Text `json:"errorMessage"`
	ValuesJson    []byte      `json:"valuesJson"`
	FilesCreated  []byte      `json:"filesCreated"`
	OutputTarget  pgtype.Text `json:"outputTarget"`
	OutputRepo    pgtype.Text `json:"outputRepo"`
	DurationMs    float64     `json:"durationMs"`
}

func (q *Queries) CreateExecutionLog(ctx context.Context, arg CreateExecutionLogParams) (ExecutionLog, error) {
	row := q.db.QueryRow(ctx, createExecutionLog,
		arg.OrgID,
		arg.TemplateName,
		arg.TemplateTitle,
		arg.Status,
		arg.CommitSha,
		arg.CommitUrl,
		arg.ErrorMessage,
		arg.ValuesJson,
		arg.FilesCreated,
		arg.OutputTarget,
		arg.OutputRepo,
		arg.DurationMs,
	)
	var i ExecutionLog
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TemplateName,
		&i.TemplateTitle,
		&i.Status,
		&i.CommitSha,
		&i.CommitUrl,
		&i.ErrorMessage,
		&i.ValuesJson,
		&i.FilesCreated,
		&i.OutputTarget,
		&i.OutputRepo,
		&i.ExecutedAt,
		&i.DurationMs,
	)
	return i, err
}

const getExecutionByID = `-- name: GetExecutionByID :one
SELECT id, org_id, template_name, template_title, status, commit_sha, commit_url, error_message, values_json, files_created, output_target, output_repo, executed_at, duration_ms FROM execution_logs WHERE id = $1 AND org_id = $2
`

type GetExecutionByIDParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"orgId"`
}

func (q *Queries) GetExecutionByID(ctx context.Context, arg GetExecutionByIDParams) (ExecutionLog, error) {
	row := q.db.QueryRow(ctx, getExecutionByID, arg.ID, arg.OrgID)
	var i ExecutionLog
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TemplateName,
		&i.TemplateTitle,
		&i.Status,
		&i.CommitSha,
		&i.CommitUrl,
		&i.ErrorMessage,
		&i.ValuesJson,
		&i.FilesCreated,
		&i.OutputTarget,
		&i.OutputRepo,
		&i.ExecutedAt,
		&i.DurationMs,
	)
	return i, err
}

const listExecutions = `-- name: ListExecutions :many
SELECT id, org_id, template_name, template_title, status, commit_sha, commit_url, error_message, values_json, files_created, output_target, output_repo, executed_at, duration_ms FROM execution_logs
WHERE org_id = $1
  AND ($4::text = '' OR template_name = $4)
  AND ($5::text = '' OR status = $5)
ORDER BY executed_at DESC
LIMIT $2 OFFSET $3
`

type ListExecutionsParams struct {
	OrgID    uuid.UUID `json:"orgId"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
	Template string    `json:"template"`
	Status   string    `json:"status"`
}

func (q *Queries) ListExecutions(ctx context.Context, arg ListExecutionsParams) ([]ExecutionLog, error) {
	rows, err := q.db.Query(ctx, listExecutions,
		arg.OrgID,
		arg.Limit,
		arg.Offset,
		arg.Template,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExecutionLog{}
	for rows.Next() {
		var i ExecutionLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TemplateName,
			&i.TemplateTitle,
			&i.Status,
			&i.CommitSha,
			&i.CommitUrl,
			&i.ErrorMessage,
			&i.ValuesJson,
			&i.FilesCreated,
			&i.OutputTarget,
			&i.OutputRepo,
			&i.ExecutedAt,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
