// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const activateMembership = `-- name: ActivateMembership :exec
UPDATE memberships SET user_id = $2, status = 'active' WHERE id = $1
`

type ActivateMembershipParams struct {
	ID     uuid.UUID     `json:"id"`
	UserID uuid.NullUUID `json:"userId"`
}

func (q *Queries) ActivateMembership(ctx context.Context, arg ActivateMembershipParams) error {
	_, err := q.db.Exec(ctx, activateMembership, arg.ID, arg.UserID)
	return err
}

const countActivePlatformEngineers = `-- name: CountActivePlatformEngineers :one
SELECT count(*) FROM memberships WHERE org_id = $1 AND role = 'platform-engineer' AND status = 'active'
`

func (q *Queries) CountActivePlatformEngineers(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActivePlatformEngineers, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (org_id, user_id, username, role, status, invited_by_user_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, user_id, username, role, status, invited_by_user_id, created_at
`

type CreateMembershipParams struct {
	OrgID           uuid.UUID     `json:"orgId"`
	UserID          uuid.NullUUID `json:"userId"`
	Username        string        `json:"username"`
	Role            string        `json:"role"`
	Status          string        `json:"status"`
	InvitedByUserID uuid.NullUUID `json:"invitedByUserId"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership,
		arg.OrgID,
		arg.UserID,
		arg.Username,
		arg.Role,
		arg.Status,
		arg.InvitedByUserID,
	)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Username,
		&i.Role,
		&i.Status,
		&i.InvitedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM memberships WHERE id = $1
`

func (q *Queries) DeleteMembership(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMembership, id)
	return err
}

const getActiveMembership = `-- name: GetActiveMembership :one
SELECT id, org_id, user_id, username, role, status, invited_by_user_id, created_at FROM memberships WHERE org_id = $1 AND user_id = $2 AND status = 'active'
`

type GetActiveMembershipParams struct {
	OrgID  uuid.UUID     `json:"orgId"`
	UserID uuid.NullUUID `json:"userId"`
}

func (q *Queries) GetActiveMembership(ctx context.Context, arg GetActiveMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getActiveMembership, arg.OrgID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Username,
		&i.Role,
		&i.Status,
		&i.InvitedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getMembershipByID = `-- name: GetMembershipByID :one
SELECT id, org_id, user_id, username, role, status, invited_by_user_id, created_at FROM memberships WHERE id = $1 AND org_id = $2
`

type GetMembershipByIDParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"orgId"`
}

func (q *Queries) GetMembershipByID(ctx context.Context, arg GetMembershipByIDParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembershipByID, arg.ID, arg.OrgID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Username,
		&i.Role,
		&i.Status,
		&i.InvitedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const listMembershipsByOrg = `-- name: ListMembershipsByOrg :many
SELECT id, org_id, user_id, username, role, status, invited_by_user_id, created_at FROM memberships WHERE org_id = $1 ORDER BY username
`

func (q *Queries) ListMembershipsByOrg(ctx context.Context, orgID uuid.UUID) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listMembershipsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Membership{}
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Username,
			&i.Role,
			&i.Status,
			&i.InvitedByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingMembershipsByUsername = `-- name: ListPendingMembershipsByUsername :many
SELECT id, org_id, user_id, username, role, status, invited_by_user_id, created_at FROM memberships WHERE lower(username) = lower($1) AND user_id IS NULL
`

func (q *Queries) ListPendingMembershipsByUsername(ctx context.Context, lower string) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listPendingMembershipsByUsername, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Membership{}
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Username,
			&i.Role,
			&i.Status,
			&i.InvitedByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const membershipExists = `-- name: MembershipExists :one
SELECT EXISTS(SELECT 1 FROM memberships WHERE org_id = $1 AND lower(username) = lower($2))
`

type MembershipExistsParams struct {
	OrgID uuid.UUID `json:"orgId"`
	Lower string    `json:"lower"`
}

func (q *Queries) MembershipExists(ctx context.Context, arg MembershipExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, membershipExists, arg.OrgID, arg.Lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateMembershipRole = `-- name: UpdateMembershipRole :one
UPDATE memberships SET role = $2 WHERE id = $1 RETURNING id, org_id, user_id, username, role, status, invited_by_user_id, created_at
`

type UpdateMembershipRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role string    `json:"role"`
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (Membership, error) {
	row := q.db.QueryRow(ctx, updateMembershipRole, arg.ID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Username,
		&i.Role,
		&i.Status,
		&i.InvitedByUserID,
		&i.CreatedAt,
	)
	return i, err
}
