// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ExecutionLog struct {
	ID            uuid.UUID   `json:"id"`
	OrgID         uuid.UUID   `json:"orgId"`
	TemplateName  string      `json:"templateName"`
	TemplateTitle string      `json:"templateTitle"`
	Status        string      `json:"status"`
	CommitSha     pgtype.Text `json:"commitSha"`
	CommitUrl     pgtype.Text `json:"commitUrl"`
	ErrorMessage  pgtype.Text `json:"errorMessage"`
	ValuesJson    []byte      `json:"valuesJson"`
	FilesCreated  []byte      `json:"filesCreated"`
	OutputTarget  pgtype.Text `json:"outputTarget"`
	OutputRepo    pgtype.Text `json:"outputRepo"`
	ExecutedAt    time.Time   `json:"executedAt"`
	DurationMs    float64     `json:"durationMs"`
}

type Membership struct {
	ID              uuid.UUID     `json:"id"`
	OrgID           uuid.UUID     `json:"orgId"`
	UserID          uuid.NullUUID `json:"userId"`
	Username        string        `json:"username"`
	Role            string        `json:"role"`
	Status          string        `json:"status"`
	InvitedByUserID uuid.NullUUID `json:"invitedByUserId"`
	CreatedAt       time.Time     `json:"createdAt"`
}

type Organization struct {
	ID                        uuid.UUID          `json:"id"`
	Name                      string             `json:"name"`
	Slug                      string             `json:"slug"`
	CatalogRepoUrl            pgtype.Text        `json:"catalogRepoUrl"`
	CatalogBranch             string             `json:"catalogBranch"`
	LastCatalogSyncAt         pgtype.Timestamptz `json:"lastCatalogSyncAt"`
	CatalogRepoTokenEncrypted pgtype.Text        `json:"catalogRepoTokenEncrypted"`
	CreatedByUserID           uuid.UUID          `json:"createdByUserId"`
	CreatedAt                 time.Time          `json:"createdAt"`
}

type OutputPreset struct {
	ID                    uuid.UUID   `json:"id"`
	OrgID                 uuid.UUID   `json:"orgId"`
	Name                  string      `json:"name"`
	Description           pgtype.Text `json:"description"`
	Type                  string      `json:"type"`
	Repo                  string      `json:"repo"`
	Branch                string      `json:"branch"`
	Path                  string      `json:"path"`
	CommitMessageTemplate pgtype.Text `json:"commitMessageTemplate"`
	GitHubTokenEnv        pgtype.Text `json:"gitHubTokenEnv"`
	CreatedAt             time.Time   `json:"createdAt"`
	UpdatedAt             time.Time   `json:"updatedAt"`
}

type ProvisioningRequest struct {
	ID               uuid.UUID          `json:"id"`
	OrgID            uuid.UUID          `json:"orgId"`
	TemplateName     string             `json:"templateName"`
	TemplateTitle    string             `json:"templateTitle"`
	Name             string             `json:"name"`
	Team             pgtype.Text        `json:"team"`
	Owner            pgtype.Text        `json:"owner"`
	Status           string             `json:"status"`
	RequiresApproval bool               `json:"requiresApproval"`
	ValuesJson       pgtype.Text        `json:"valuesJson"`
	SubmittedBy      pgtype.Text        `json:"submittedBy"`
	ApprovedBy       pgtype.Text        `json:"approvedBy"`
	ApprovedAt       pgtype.Timestamptz `json:"approvedAt"`
	RejectionReason  pgtype.Text        `json:"rejectionReason"`
	CreatedAt        time.Time          `json:"createdAt"`
	CompletedAt      pgtype.Timestamptz `json:"completedAt"`
	ErrorMessage     pgtype.Text        `json:"errorMessage"`
	CommitSha        pgtype.Text        `json:"commitSha"`
	CommitUrl        pgtype.Text        `json:"commitUrl"`
	ExecutionLogID   uuid.NullUUID      `json:"executionLogId"`
}

type Service struct {
	ID           uuid.UUID   `json:"id"`
	OrgID        uuid.UUID   `json:"orgId"`
	Name         string      `json:"name"`
	TemplateName pgtype.Text `json:"templateName"`
	ServiceType  pgtype.Text `json:"serviceType"`
	Team         pgtype.Text `json:"team"`
	Owner        pgtype.Text `json:"owner"`
	Lifecycle    string      `json:"lifecycle"`
	Description  pgtype.Text `json:"description"`
	RepoUrl      pgtype.Text `json:"repoUrl"`
	CreatedAt    time.Time   `json:"createdAt"`
	RequestID    uuid.UUID   `json:"requestId"`
}

type User struct {
	ID             uuid.UUID   `json:"id"`
	ZitadelSubject string      `json:"zitadelSubject"`
	Username       string      `json:"username"`
	DisplayName    string      `json:"displayName"`
	Email          pgtype.Text `json:"email"`
	CreatedAt      time.Time   `json:"createdAt"`
	LastLoginAt    time.Time   `json:"lastLoginAt"`
	QuillUserID    pgtype.Text `json:"quillUserId"`
}
