// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, slug, created_by_user_id)
VALUES ($1, $2, $3)
RETURNING id, name, slug, catalog_repo_url, catalog_branch, last_catalog_sync_at, catalog_repo_token_encrypted, created_by_user_id, created_at
`

type CreateOrganizationParams struct {
	Name            string    `json:"name"`
	Slug            string    `json:"slug"`
	CreatedByUserID uuid.UUID `json:"createdByUserId"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Slug, arg.CreatedByUserID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CatalogRepoUrl,
		&i.CatalogBranch,
		&i.LastCatalogSyncAt,
		&i.CatalogRepoTokenEncrypted,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, slug, catalog_repo_url, catalog_branch, last_catalog_sync_at, catalog_repo_token_encrypted, created_by_user_id, created_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CatalogRepoUrl,
		&i.CatalogBranch,
		&i.LastCatalogSyncAt,
		&i.CatalogRepoTokenEncrypted,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const listOrganizationsForUser = `-- name: ListOrganizationsForUser :many
SELECT o.id, o.name, o.slug, m.role
FROM memberships m
JOIN organizations o ON o.id = m.org_id
WHERE m.user_id = $1 AND m.status = 'active'
ORDER BY o.name
`

type ListOrganizationsForUserRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Slug string    `json:"slug"`
	Role string    `json:"role"`
}

func (q *Queries) ListOrganizationsForUser(ctx context.Context, userID uuid.NullUUID) ([]ListOrganizationsForUserRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationsForUserRow{}
	for rows.Next() {
		var i ListOrganizationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const organizationSlugExists = `-- name: OrganizationSlugExists :one
SELECT EXISTS(SELECT 1 FROM organizations WHERE slug = $1)
`

func (q *Queries) OrganizationSlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, organizationSlugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setOrganizationCatalogSynced = `-- name: SetOrganizationCatalogSynced :exec
UPDATE organizations SET last_catalog_sync_at = $2 WHERE id = $1
`

type SetOrganizationCatalogSyncedParams struct {
	ID                uuid.UUID          `json:"id"`
	LastCatalogSyncAt pgtype.Timestamptz `json:"lastCatalogSyncAt"`
}

func (q *Queries) SetOrganizationCatalogSynced(ctx context.Context, arg SetOrganizationCatalogSyncedParams) error {
	_, err := q.db.Exec(ctx, setOrganizationCatalogSynced, arg.ID, arg.LastCatalogSyncAt)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET name = $2,
    catalog_repo_url = $3,
    catalog_branch = $4,
    catalog_repo_token_encrypted = $5
WHERE id = $1
RETURNING id, name, slug, catalog_repo_url, catalog_branch, last_catalog_sync_at, catalog_repo_token_encrypted, created_by_user_id, created_at
`

type UpdateOrganizationParams struct {
	ID                        uuid.UUID   `json:"id"`
	Name                      string      `json:"name"`
	CatalogRepoUrl            pgtype.Text `json:"catalogRepoUrl"`
	CatalogBranch             string      `json:"catalogBranch"`
	CatalogRepoTokenEncrypted pgtype.Text `json:"catalogRepoTokenEncrypted"`
}

// Callers resolve the final catalog_repo_token_encrypted value themselves
// (encrypt / clear / keep-existing) before calling this — see server/orgs.go.
func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.ID,
		arg.Name,
		arg.CatalogRepoUrl,
		arg.CatalogBranch,
		arg.CatalogRepoTokenEncrypted,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CatalogRepoUrl,
		&i.CatalogBranch,
		&i.LastCatalogSyncAt,
		&i.CatalogRepoTokenEncrypted,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return i, err
}
