// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: presets.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPreset = `-- name: CreatePreset :one
INSERT INTO output_presets (org_id, name, description, type, repo, branch, path, commit_message_template, git_hub_token_env)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, org_id, name, description, type, repo, branch, path, commit_message_template, git_hub_token_env, created_at, updated_at
`

type CreatePresetParams struct {
	OrgID                 uuid.UUID   `json:"orgId"`
	Name                  string      `json:"name"`
	Description           pgtype.Text `json:"description"`
	Type                  string      `json:"type"`
	Repo                  string      `json:"repo"`
	Branch                string      `json:"branch"`
	Path                  string      `json:"path"`
	CommitMessageTemplate pgtype.Text `json:"commitMessageTemplate"`
	GitHubTokenEnv        pgtype.Text `json:"gitHubTokenEnv"`
}

func (q *Queries) CreatePreset(ctx context.Context, arg CreatePresetParams) (OutputPreset, error) {
	row := q.db.QueryRow(ctx, createPreset,
		arg.OrgID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Repo,
		arg.Branch,
		arg.Path,
		arg.CommitMessageTemplate,
		arg.GitHubTokenEnv,
	)
	var i OutputPreset
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Repo,
		&i.Branch,
		&i.Path,
		&i.CommitMessageTemplate,
		&i.GitHubTokenEnv,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePreset = `-- name: DeletePreset :exec
DELETE FROM output_presets WHERE id = $1 AND org_id = $2
`

type DeletePresetParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"orgId"`
}

func (q *Queries) DeletePreset(ctx context.Context, arg DeletePresetParams) error {
	_, err := q.db.Exec(ctx, deletePreset, arg.ID, arg.OrgID)
	return err
}

const getPresetByID = `-- name: GetPresetByID :one
SELECT id, org_id, name, description, type, repo, branch, path, commit_message_template, git_hub_token_env, created_at, updated_at FROM output_presets WHERE id = $1 AND org_id = $2
`

type GetPresetByIDParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"orgId"`
}

func (q *Queries) GetPresetByID(ctx context.Context, arg GetPresetByIDParams) (OutputPreset, error) {
	row := q.db.QueryRow(ctx, getPresetByID, arg.ID, arg.OrgID)
	var i OutputPreset
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Repo,
		&i.Branch,
		&i.Path,
		&i.CommitMessageTemplate,
		&i.GitHubTokenEnv,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPresetByName = `-- name: GetPresetByName :one
SELECT id, org_id, name, description, type, repo, branch, path, commit_message_template, git_hub_token_env, created_at, updated_at FROM output_presets WHERE org_id = $1 AND name = $2
`

type GetPresetByNameParams struct {
	OrgID uuid.UUID `json:"orgId"`
	Name  string    `json:"name"`
}

func (q *Queries) GetPresetByName(ctx context.Context, arg GetPresetByNameParams) (OutputPreset, error) {
	row := q.db.QueryRow(ctx, getPresetByName, arg.OrgID, arg.Name)
	var i OutputPreset
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Repo,
		&i.Branch,
		&i.Path,
		&i.CommitMessageTemplate,
		&i.GitHubTokenEnv,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPresets = `-- name: ListPresets :many
SELECT id, org_id, name, description, type, repo, branch, path, commit_message_template, git_hub_token_env, created_at, updated_at FROM output_presets WHERE org_id = $1 ORDER BY name
`

func (q *Queries) ListPresets(ctx context.Context, orgID uuid.UUID) ([]OutputPreset, error) {
	rows, err := q.db.Query(ctx, listPresets, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutputPreset{}
	for rows.Next() {
		var i OutputPreset
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Repo,
			&i.Branch,
			&i.Path,
			&i.CommitMessageTemplate,
			&i.GitHubTokenEnv,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePreset = `-- name: UpdatePreset :one
UPDATE output_presets
SET name = $3, description = $4, type = $5, repo = $6, branch = $7, path = $8,
    commit_message_template = $9, git_hub_token_env = $10, updated_at = now()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, description, type, repo, branch, path, commit_message_template, git_hub_token_env, created_at, updated_at
`

type UpdatePresetParams struct {
	ID                    uuid.UUID   `json:"id"`
	OrgID                 uuid.UUID   `json:"orgId"`
	Name                  string      `json:"name"`
	Description           pgtype.Text `json:"description"`
	Type                  string      `json:"type"`
	Repo                  string      `json:"repo"`
	Branch                string      `json:"branch"`
	Path                  string      `json:"path"`
	CommitMessageTemplate pgtype.Text `json:"commitMessageTemplate"`
	GitHubTokenEnv        pgtype.Text `json:"gitHubTokenEnv"`
}

func (q *Queries) UpdatePreset(ctx context.Context, arg UpdatePresetParams) (OutputPreset, error) {
	row := q.db.QueryRow(ctx, updatePreset,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Repo,
		arg.Branch,
		arg.Path,
		arg.CommitMessageTemplate,
		arg.GitHubTokenEnv,
	)
	var i OutputPreset
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Repo,
		&i.Branch,
		&i.Path,
		&i.CommitMessageTemplate,
		&i.GitHubTokenEnv,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
