// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ActivateMembership(ctx context.Context, arg ActivateMembershipParams) error
	ApproveRequest(ctx context.Context, arg ApproveRequestParams) (ProvisioningRequest, error)
	CompleteRequest(ctx context.Context, arg CompleteRequestParams) (ProvisioningRequest, error)
	CountActivePlatformEngineers(ctx context.Context, orgID uuid.UUID) (int64, error)
	CountExecutions(ctx context.Context, arg CountExecutionsParams) (int64, error)
	CountServices(ctx context.Context, arg CountServicesParams) (int64, error)
	CreateExecutionLog(ctx context.Context, arg CreateExecutionLogParams) (ExecutionLog, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreatePreset(ctx context.Context, arg CreatePresetParams) (OutputPreset, error)
	CreateRequest(ctx context.Context, arg CreateRequestParams) (ProvisioningRequest, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteMembership(ctx context.Context, id uuid.UUID) error
	DeletePreset(ctx context.Context, arg DeletePresetParams) error
	GetActiveMembership(ctx context.Context, arg GetActiveMembershipParams) (Membership, error)
	GetExecutionByID(ctx context.Context, arg GetExecutionByIDParams) (ExecutionLog, error)
	GetMembershipByID(ctx context.Context, arg GetMembershipByIDParams) (Membership, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetPresetByID(ctx context.Context, arg GetPresetByIDParams) (OutputPreset, error)
	GetPresetByName(ctx context.Context, arg GetPresetByNameParams) (OutputPreset, error)
	GetRequestByID(ctx context.Context, arg GetRequestByIDParams) (ProvisioningRequest, error)
	GetServiceByID(ctx context.Context, arg GetServiceByIDParams) (Service, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, lower string) (User, error)
	GetUserByZitadelSubject(ctx context.Context, zitadelSubject string) (User, error)
	ListExecutions(ctx context.Context, arg ListExecutionsParams) ([]ExecutionLog, error)
	ListMembershipsByOrg(ctx context.Context, orgID uuid.UUID) ([]Membership, error)
	ListOrganizationsForUser(ctx context.Context, userID uuid.NullUUID) ([]ListOrganizationsForUserRow, error)
	ListPendingMembershipsByUsername(ctx context.Context, lower string) ([]Membership, error)
	ListPresets(ctx context.Context, orgID uuid.UUID) ([]OutputPreset, error)
	ListRequests(ctx context.Context, arg ListRequestsParams) ([]ProvisioningRequest, error)
	ListServices(ctx context.Context, arg ListServicesParams) ([]Service, error)
	MembershipExists(ctx context.Context, arg MembershipExistsParams) (bool, error)
	OrganizationSlugExists(ctx context.Context, slug string) (bool, error)
	RejectRequest(ctx context.Context, arg RejectRequestParams) (ProvisioningRequest, error)
	SetOrganizationCatalogSynced(ctx context.Context, arg SetOrganizationCatalogSyncedParams) error
	SetQuillUserID(ctx context.Context, arg SetQuillUserIDParams) error
	StartRetry(ctx context.Context, id uuid.UUID) (ProvisioningRequest, error)
	TouchUserLogin(ctx context.Context, arg TouchUserLoginParams) (User, error)
	UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (Membership, error)
	// Callers resolve the final catalog_repo_token_encrypted value themselves
	// (encrypt / clear / keep-existing) before calling this — see server/orgs.go.
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpdatePreset(ctx context.Context, arg UpdatePresetParams) (OutputPreset, error)
}

var _ Querier = (*Queries)(nil)
