// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveRequest = `-- name: ApproveRequest :one
UPDATE provisioning_requests
SET status = 'provisioning', approved_by = $2, approved_at = now()
WHERE id = $1
RETURNING id, org_id, template_name, template_title, name, team, owner, status, requires_approval, values_json, submitted_by, approved_by, approved_at, rejection_reason, created_at, completed_at, error_message, commit_sha, commit_url, execution_log_id
`

type ApproveRequestParams struct {
	ID         uuid.UUID   `json:"id"`
	ApprovedBy pgtype.Text `json:"approvedBy"`
}

func (q *Queries) ApproveRequest(ctx context.Context, arg ApproveRequestParams) (ProvisioningRequest, error) {
	row := q.db.QueryRow(ctx, approveRequest, arg.ID, arg.ApprovedBy)
	var i ProvisioningRequest
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TemplateName,
		&i.TemplateTitle,
		&i.Name,
		&i.Team,
		&i.Owner,
		&i.Status,
		&i.RequiresApproval,
		&i.ValuesJson,
		&i.SubmittedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CommitSha,
		&i.CommitUrl,
		&i.ExecutionLogID,
	)
	return i, err
}

const completeRequest = `-- name: CompleteRequest :one
UPDATE provisioning_requests
SET status = $2,
    execution_log_id = $3,
    commit_sha = $4,
    commit_url = $5,
    completed_at = now(),
    error_message = $6
WHERE id = $1
RETURNING id, org_id, template_name, template_title, name, team, owner, status, requires_approval, values_json, submitted_by, approved_by, approved_at, rejection_reason, created_at, completed_at, error_message, commit_sha, commit_url, execution_log_id
`

type CompleteRequestParams struct {
	ID             uuid.UUID     `json:"id"`
	Status         string        `json:"status"`
	ExecutionLogID uuid.NullUUID `json:"executionLogId"`
	CommitSha      pgtype.Text   `json:"commitSha"`
	CommitUrl      pgtype.Text   `json:"commitUrl"`
	ErrorMessage   pgtype.Text   `json:"errorMessage"`
}

func (q *Queries) CompleteRequest(ctx context.Context, arg CompleteRequestParams) (ProvisioningRequest, error) {
	row := q.db.QueryRow(ctx, completeRequest,
		arg.ID,
		arg.Status,
		arg.ExecutionLogID,
		arg.CommitSha,
		arg.CommitUrl,
		arg.ErrorMessage,
	)
	var i ProvisioningRequest
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TemplateName,
		&i.TemplateTitle,
		&i.Name,
		&i.Team,
		&i.Owner,
		&i.Status,
		&i.RequiresApproval,
		&i.ValuesJson,
		&i.SubmittedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CommitSha,
		&i.CommitUrl,
		&i.ExecutionLogID,
	)
	return i, err
}

const createRequest = `-- name: CreateRequest :one
INSERT INTO provisioning_requests
    (org_id, template_name, template_title, name, team, owner, submitted_by, requires_approval, values_json, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, org_id, template_name, template_title, name, team, owner, status, requires_approval, values_json, submitted_by, approved_by, approved_at, rejection_reason, created_at, completed_at, error_message, commit_sha, commit_url, execution_log_id
`

type CreateRequestParams struct {
	OrgID            uuid.UUID   `json:"orgId"`
	TemplateName     string      `json:"templateName"`
	TemplateTitle    string      `json:"templateTitle"`
	Name             string      `json:"name"`
	Team             pgtype.Text `json:"team"`
	Owner            pgtype.Text `json:"owner"`
	SubmittedBy      pgtype.Text `json:"submittedBy"`
	RequiresApproval bool        `json:"requiresApproval"`
	ValuesJson       pgtype.Text `json:"valuesJson"`
	Status           string      `json:"status"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (ProvisioningRequest, error) {
	row := q.db.QueryRow(ctx, createRequest,
		arg.OrgID,
		arg.TemplateName,
		arg.TemplateTitle,
		arg.Name,
		arg.Team,
		arg.Owner,
		arg.SubmittedBy,
		arg.RequiresApproval,
		arg.ValuesJson,
		arg.Status,
	)
	var i ProvisioningRequest
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TemplateName,
		&i.TemplateTitle,
		&i.Name,
		&i.Team,
		&i.Owner,
		&i.Status,
		&i.RequiresApproval,
		&i.ValuesJson,
		&i.SubmittedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CommitSha,
		&i.CommitUrl,
		&i.ExecutionLogID,
	)
	return i, err
}

const getRequestByID = `-- name: GetRequestByID :one
SELECT id, org_id, template_name, template_title, name, team, owner, status, requires_approval, values_json, submitted_by, approved_by, approved_at, rejection_reason, created_at, completed_at, error_message, commit_sha, commit_url, execution_log_id FROM provisioning_requests WHERE id = $1 AND org_id = $2
`

type GetRequestByIDParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"orgId"`
}

func (q *Queries) GetRequestByID(ctx context.Context, arg GetRequestByIDParams) (ProvisioningRequest, error) {
	row := q.db.QueryRow(ctx, getRequestByID, arg.ID, arg.OrgID)
	var i ProvisioningRequest
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TemplateName,
		&i.TemplateTitle,
		&i.Name,
		&i.Team,
		&i.Owner,
		&i.Status,
		&i.RequiresApproval,
		&i.ValuesJson,
		&i.SubmittedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CommitSha,
		&i.CommitUrl,
		&i.ExecutionLogID,
	)
	return i, err
}

const listRequests = `-- name: ListRequests :many
SELECT id, org_id, template_name, template_title, name, team, owner, status, requires_approval, values_json, submitted_by, approved_by, approved_at, rejection_reason, created_at, completed_at, error_message, commit_sha, commit_url, execution_log_id FROM provisioning_requests
WHERE org_id = $1
  AND ($2::text = '' OR status = $2)
ORDER BY created_at DESC
`

type ListRequestsParams struct {
	OrgID  uuid.UUID `json:"orgId"`
	Status string    `json:"status"`
}

func (q *Queries) ListRequests(ctx context.Context, arg ListRequestsParams) ([]ProvisioningRequest, error) {
	rows, err := q.db.Query(ctx, listRequests, arg.OrgID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProvisioningRequest{}
	for rows.Next() {
		var i ProvisioningRequest
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TemplateName,
			&i.TemplateTitle,
			&i.Name,
			&i.Team,
			&i.Owner,
			&i.Status,
			&i.RequiresApproval,
			&i.ValuesJson,
			&i.SubmittedBy,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.CommitSha,
			&i.CommitUrl,
			&i.ExecutionLogID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectRequest = `-- name: RejectRequest :one
UPDATE provisioning_requests
SET status = 'rejected', rejection_reason = $2, approved_by = $3, completed_at = now()
WHERE id = $1
RETURNING id, org_id, template_name, template_title, name, team, owner, status, requires_approval, values_json, submitted_by, approved_by, approved_at, rejection_reason, created_at, completed_at, error_message, commit_sha, commit_url, execution_log_id
`

type RejectRequestParams struct {
	ID              uuid.UUID   `json:"id"`
	RejectionReason pgtype.Text `json:"rejectionReason"`
	ApprovedBy      pgtype.Text `json:"approvedBy"`
}

func (q *Queries) RejectRequest(ctx context.Context, arg RejectRequestParams) (ProvisioningRequest, error) {
	row := q.db.QueryRow(ctx, rejectRequest, arg.ID, arg.RejectionReason, arg.ApprovedBy)
	var i ProvisioningRequest
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TemplateName,
		&i.TemplateTitle,
		&i.Name,
		&i.Team,
		&i.Owner,
		&i.Status,
		&i.RequiresApproval,
		&i.ValuesJson,
		&i.SubmittedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CommitSha,
		&i.CommitUrl,
		&i.ExecutionLogID,
	)
	return i, err
}

const startRetry = `-- name: StartRetry :one
UPDATE provisioning_requests
SET status = 'provisioning', error_message = NULL
WHERE id = $1
RETURNING id, org_id, template_name, template_title, name, team, owner, status, requires_approval, values_json, submitted_by, approved_by, approved_at, rejection_reason, created_at, completed_at, error_message, commit_sha, commit_url, execution_log_id
`

func (q *Queries) StartRetry(ctx context.Context, id uuid.UUID) (ProvisioningRequest, error) {
	row := q.db.QueryRow(ctx, startRetry, id)
	var i ProvisioningRequest
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TemplateName,
		&i.TemplateTitle,
		&i.Name,
		&i.Team,
		&i.Owner,
		&i.Status,
		&i.RequiresApproval,
		&i.ValuesJson,
		&i.SubmittedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CommitSha,
		&i.CommitUrl,
		&i.ExecutionLogID,
	)
	return i, err
}
