// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countServices = `-- name: CountServices :one
SELECT count(*) FROM services
WHERE org_id = $1
  AND ($2::text = '' OR team = $2)
  AND (
    $3::text = ''
    OR name ILIKE '%' || $3 || '%'
    OR description ILIKE '%' || $3 || '%'
  )
`

type CountServicesParams struct {
	OrgID  uuid.UUID `json:"orgId"`
	Team   string    `json:"team"`
	Search string    `json:"search"`
}

func (q *Queries) CountServices(ctx context.Context, arg CountServicesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countServices, arg.OrgID, arg.Team, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (org_id, name, template_name, service_type, team, owner, lifecycle, description, repo_url, request_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, org_id, name, template_name, service_type, team, owner, lifecycle, description, repo_url, created_at, request_id
`

type CreateServiceParams struct {
	OrgID        uuid.UUID   `json:"orgId"`
	Name         string      `json:"name"`
	TemplateName pgtype.Text `json:"templateName"`
	ServiceType  pgtype.Text `json:"serviceType"`
	Team         pgtype.Text `json:"team"`
	Owner        pgtype.Text `json:"owner"`
	Lifecycle    string      `json:"lifecycle"`
	Description  pgtype.Text `json:"description"`
	RepoUrl      pgtype.Text `json:"repoUrl"`
	RequestID    uuid.UUID   `json:"requestId"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.OrgID,
		arg.Name,
		arg.TemplateName,
		arg.ServiceType,
		arg.Team,
		arg.Owner,
		arg.Lifecycle,
		arg.Description,
		arg.RepoUrl,
		arg.RequestID,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TemplateName,
		&i.ServiceType,
		&i.Team,
		&i.Owner,
		&i.Lifecycle,
		&i.Description,
		&i.RepoUrl,
		&i.CreatedAt,
		&i.RequestID,
	)
	return i, err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, org_id, name, template_name, service_type, team, owner, lifecycle, description, repo_url, created_at, request_id FROM services WHERE id = $1 AND org_id = $2
`

type GetServiceByIDParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"orgId"`
}

func (q *Queries) GetServiceByID(ctx context.Context, arg GetServiceByIDParams) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, arg.ID, arg.OrgID)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TemplateName,
		&i.ServiceType,
		&i.Team,
		&i.Owner,
		&i.Lifecycle,
		&i.Description,
		&i.RepoUrl,
		&i.CreatedAt,
		&i.RequestID,
	)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT id, org_id, name, template_name, service_type, team, owner, lifecycle, description, repo_url, created_at, request_id FROM services
WHERE org_id = $1
  AND ($4::text = '' OR team = $4)
  AND (
    $5::text = ''
    OR name ILIKE '%' || $5 || '%'
    OR description ILIKE '%' || $5 || '%'
  )
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListServicesParams struct {
	OrgID  uuid.UUID `json:"orgId"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
	Team   string    `json:"team"`
	Search string    `json:"search"`
}

func (q *Queries) ListServices(ctx context.Context, arg ListServicesParams) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServices,
		arg.OrgID,
		arg.Limit,
		arg.Offset,
		arg.Team,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.TemplateName,
			&i.ServiceType,
			&i.Team,
			&i.Owner,
			&i.Lifecycle,
			&i.Description,
			&i.RepoUrl,
			&i.CreatedAt,
			&i.RequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
