// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (zitadel_subject, username, display_name, email)
VALUES ($1, $2, $3, $4)
RETURNING id, zitadel_subject, username, display_name, email, created_at, last_login_at, quill_user_id
`

type CreateUserParams struct {
	ZitadelSubject string      `json:"zitadelSubject"`
	Username       string      `json:"username"`
	DisplayName    string      `json:"displayName"`
	Email          pgtype.Text `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ZitadelSubject,
		arg.Username,
		arg.DisplayName,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ZitadelSubject,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.QuillUserID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, zitadel_subject, username, display_name, email, created_at, last_login_at, quill_user_id FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ZitadelSubject,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.QuillUserID,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, zitadel_subject, username, display_name, email, created_at, last_login_at, quill_user_id FROM users WHERE lower(username) = lower($1)
`

func (q *Queries) GetUserByUsername(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ZitadelSubject,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.QuillUserID,
	)
	return i, err
}

const getUserByZitadelSubject = `-- name: GetUserByZitadelSubject :one
SELECT id, zitadel_subject, username, display_name, email, created_at, last_login_at, quill_user_id FROM users WHERE zitadel_subject = $1
`

func (q *Queries) GetUserByZitadelSubject(ctx context.Context, zitadelSubject string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByZitadelSubject, zitadelSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ZitadelSubject,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.QuillUserID,
	)
	return i, err
}

const setQuillUserID = `-- name: SetQuillUserID :exec
UPDATE users SET quill_user_id = $2 WHERE id = $1 AND quill_user_id IS NULL
`

type SetQuillUserIDParams struct {
	ID          uuid.UUID   `json:"id"`
	QuillUserID pgtype.Text `json:"quillUserId"`
}

func (q *Queries) SetQuillUserID(ctx context.Context, arg SetQuillUserIDParams) error {
	_, err := q.db.Exec(ctx, setQuillUserID, arg.ID, arg.QuillUserID)
	return err
}

const touchUserLogin = `-- name: TouchUserLogin :one
UPDATE users
SET username = $2, display_name = $3, email = $4, last_login_at = now()
WHERE id = $1
RETURNING id, zitadel_subject, username, display_name, email, created_at, last_login_at, quill_user_id
`

type TouchUserLoginParams struct {
	ID          uuid.UUID   `json:"id"`
	Username    string      `json:"username"`
	DisplayName string      `json:"displayName"`
	Email       pgtype.Text `json:"email"`
}

func (q *Queries) TouchUserLogin(ctx context.Context, arg TouchUserLoginParams) (User, error) {
	row := q.db.QueryRow(ctx, touchUserLogin,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ZitadelSubject,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.QuillUserID,
	)
	return i, err
}
